[sources.postgres.credentials]
database = #ENTER NAME OF DATABASE
password = #ENTER PASSWORD FOR DATABASE FOR THIS USERNAME 
username = #ENTER USERNAME FOR DATABASE 
host = #LOCALHOST OR NAME OF SERVICE IF USING DOCKER COMPOSE, NOT THE CONTAINER NAME 
port = 5432
connect_timeout = 15

[destination.postgres.credentials]
database = #ENTER NAME OF DATABASE
password = #ENTER PASSWORD FOR DATABASE FOR THIS USERNAME 
username = #ENTER USERNAME FOR DATABASE 
host = #LOCALHOST OR NAME OF SERVICE IF USING DOCKER COMPOSE, NOT THE CONTAINER NAME 
port = 5432
connect_timeout = 15
